---
name: SQLite Web zigbee
version: dev
slug: sqlite-web-zigbee
description: Explore your zigbee SQLite database
url: https://github.com/jlsjonas/addon-sqlite-web/tree/main/README.md
ingress: true
advanced: true
panel_icon: mdi:database
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
